package proy.modelo.entidad;
// Generated 13/06/2015 11:03:19 AM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private short idCategoria;
     private String nombreCat;

    public Categoria() {
    }

	
    public Categoria(short idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(short idCategoria, String nombreCat) {
       this.idCategoria = idCategoria;
       this.nombreCat = nombreCat;
    }
   
    public short getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(short idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCat() {
        return this.nombreCat;
    }
    
    public void setNombreCat(String nombreCat) {
        this.nombreCat = nombreCat;
    }




}


