package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContratoPensionista generated by hbm2java
 */
public class ContratoPensionista  implements java.io.Serializable {


     private short idContrato;
     private Persona persona;
     private Usuario usuario;
     private Date fechaInicio;
     private Date fechaFin;
     private String precioPension;
     private Date fechaPago;
     private String estado;
     private Set controlPensionistas = new HashSet(0);

    public ContratoPensionista() {
        
    }

	
    public ContratoPensionista(short idContrato) {
        this.idContrato = idContrato;
    }
    public ContratoPensionista(short idContrato, Persona persona, Usuario usuario, Date fechaInicio, Date fechaFin, String precioPension, Date fechaPago, String estado, Set controlPensionistas) {
       this.idContrato = idContrato;
       this.persona = persona;
       this.usuario = usuario;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.precioPension = precioPension;
       this.fechaPago = fechaPago;
       this.estado = estado;
       this.controlPensionistas = controlPensionistas;
    }
   
    public short getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(short idContrato) {
        this.idContrato = idContrato;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getPrecioPension() {
        return this.precioPension;
    }
    
    public void setPrecioPension(String precioPension) {
        this.precioPension = precioPension;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getControlPensionistas() {
        return this.controlPensionistas;
    }
    
    public void setControlPensionistas(Set controlPensionistas) {
        this.controlPensionistas = controlPensionistas;
    }




}


