package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ControlPensionistaId generated by hbm2java
 */
public class ControlPensionistaId  implements java.io.Serializable {


     private short idContrato;
     private Date fecha;

    public ControlPensionistaId() {
    }

    public ControlPensionistaId(short idContrato, Date fecha) {
       this.idContrato = idContrato;
       this.fecha = fecha;
    }
   
    public short getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(short idContrato) {
        this.idContrato = idContrato;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ControlPensionistaId) ) return false;
		 ControlPensionistaId castOther = ( ControlPensionistaId ) other; 
         
		 return (this.getIdContrato()==castOther.getIdContrato())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdContrato();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


