package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private DetalleVentaId id;
     private Producto producto;
     private Venta venta;
     private String precioUnitario;
     private String cantPlato;
     private String precioTotal;

    public DetalleVenta() {
    }

	
    public DetalleVenta(DetalleVentaId id, Producto producto, Venta venta) {
        this.id = id;
        this.producto = producto;
        this.venta = venta;
    }
    public DetalleVenta(DetalleVentaId id, Producto producto, Venta venta, String precioUnitario, String cantPlato, String precioTotal) {
       this.id = id;
       this.producto = producto;
       this.venta = venta;
       this.precioUnitario = precioUnitario;
       this.cantPlato = cantPlato;
       this.precioTotal = precioTotal;
    }
   
    public DetalleVentaId getId() {
        return this.id;
    }
    
    public void setId(DetalleVentaId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public String getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(String precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getCantPlato() {
        return this.cantPlato;
    }
    
    public void setCantPlato(String cantPlato) {
        this.cantPlato = cantPlato;
    }
    public String getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(String precioTotal) {
        this.precioTotal = precioTotal;
    }




}


