package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private short idPersona;
     private String nombres;
     private String apellidos;
     private String dni;
     private String NCelular;
     private String direccion;
     private Usuario usuario;
     private Set ventas = new HashSet(0);
     private Set contratoPensionistas = new HashSet(0);

    public Persona() {
    }

	
    public Persona(short idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(short idPersona, String nombres, String apellidos, String dni, String NCelular, String direccion, Usuario usuario, Set ventas, Set contratoPensionistas) {
       this.idPersona = idPersona;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
       this.NCelular = NCelular;
       this.direccion = direccion;
       this.usuario = usuario;
       this.ventas = ventas;
       this.contratoPensionistas = contratoPensionistas;
    }
   
    public short getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(short idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNCelular() {
        return this.NCelular;
    }
    
    public void setNCelular(String NCelular) {
        this.NCelular = NCelular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getContratoPensionistas() {
        return this.contratoPensionistas;
    }
    
    public void setContratoPensionistas(Set contratoPensionistas) {
        this.contratoPensionistas = contratoPensionistas;
    }




}


