package proy.modelo.entidad;
// Generated 15/06/2015 10:28:30 PM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona {


     private String idPersona;
     private String nombres;
     private String apellidos;
     private String dni;
     private String NCelular;
     private String direccion;

    public Persona() {
    }
    
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNCelular() {
        return this.NCelular;
    }
    
    public void setNCelular(String NCelular) {
        this.NCelular = NCelular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


