package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Usuario usuario;
     private Categoria categoria;
     private String nombreProducto;
     private String precioPensionista;
     private String precioAVarios;
     private String stock;
     private Set detalleVentas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(int idProducto, Usuario usuario, Categoria categoria, String nombreProducto, String precioPensionista, String precioAVarios, String stock, Set detalleVentas) {
       this.idProducto = idProducto;
       this.usuario = usuario;
       this.categoria = categoria;
       this.nombreProducto = nombreProducto;
       this.precioPensionista = precioPensionista;
       this.precioAVarios = precioAVarios;
       this.stock = stock;
       this.detalleVentas = detalleVentas;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getPrecioPensionista() {
        return this.precioPensionista;
    }
    
    public void setPrecioPensionista(String precioPensionista) {
        this.precioPensionista = precioPensionista;
    }
    public String getPrecioAVarios() {
        return this.precioAVarios;
    }
    
    public void setPrecioAVarios(String precioAVarios) {
        this.precioAVarios = precioAVarios;
    }
    public String getStock() {
        return this.stock;
    }
    
    public void setStock(String stock) {
        this.stock = stock;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


