package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private short idRol;
     private String nombreRol;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(short idRol) {
        this.idRol = idRol;
    }
    public Rol(short idRol, String nombreRol, Set usuarios) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
   
    public short getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(short idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


