package proy.modelo.entidad;
// Generated 15/06/2015 10:28:30 PM by Hibernate Tools 4.3.1



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private short idRol;
     private String nombreRol;

    public Rol() {
    }

	
    public Rol(short idRol) {
        this.idRol = idRol;
    }
    public Rol(short idRol, String nombreRol) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
    }
   
    public short getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(short idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }




}


