package proy.modelo.entidad;
// Generated 28/05/2015 08:11:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private short idVenta;
     private Persona persona;
     private Usuario usuario;
     private String numero;
     private Date fechaVenta;
     private String tipo;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(short idVenta) {
        this.idVenta = idVenta;
    }
    public Venta(short idVenta, Persona persona, Usuario usuario, String numero, Date fechaVenta, String tipo, Set detalleVentas) {
       this.idVenta = idVenta;
       this.persona = persona;
       this.usuario = usuario;
       this.numero = numero;
       this.fechaVenta = fechaVenta;
       this.tipo = tipo;
       this.detalleVentas = detalleVentas;
    }
   
    public short getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(short idVenta) {
        this.idVenta = idVenta;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


